#!/bin/sh

. /etc/formfactor/config

if [ "$HAVE_TOUCHSCREEN" = "1" ]; then
    SHOWCURSOR="no"
else
    SHOWCURSOR="yes"
fi

if [ "$HAVE_KEYBOARD" = "1" ]; then
    KEYBOARD_APPLET=""
else
    KEYBOARD_APPLET="keyboard"
fi

# Disable all DPMS standby / suspend / sleep modes by setting timings to 0.
# Disabling DPMS entirely does NOT work as Occurity uses DPMS to turn the monitor off and thereby enables DPMS again.
xset dpms 0 0 0
# Disable screensaver
xset s off

matchbox-desktop &

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

START_APPLETS=showdesktop,windowselector
END_APPLETS=$KEYBOARD_APPLET,systray,startup-notify,notify
END_APPLETS=clock,$END_APPLETS

# matchbox-panel --start-applets $START_APPLETS --end-applets $END_APPLETS &

exec matchbox-window-manager -theme Sato -use_cursor $SHOWCURSOR $@
